name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: action-git-diff-suggestions
    uses: getsentry/action-git-diff-suggestions@v1
            
